DROP TABLE IF EXISTS COMPANIES;

CREATE TABLE COMPANIES (
    ID_COMPANY INT PRIMARY KEY,
    ID_HOLDING INT DEFAULT 0,
    COMPANY_NAME VARCHAR(100),
    COMPANY_ADDRESS VARCHAR(100),
    COMPANY_CP VARCHAR(10),
    COMPANY_CITY VARCHAR(50)
)

DROP TABLE IF EXISTS PAYMENTS;

CREATE TABLE PAYMENTS (
    ID_PAYMENT INT PRIMARY KEY NOT NULL,
    ID_PURCHASE INT DEFAULT 0,
    PMT_NUM VARCHAR(100),
    PMT_HT INT NOT NULL DEFAULT 0,
    PMT_TTC INT NOT NULL DEFAULT 0
)

DROP TABLE IF EXISTS PURCHASE;

CREATE TABLE PURCHASE (
    ID_PURCHASE INT PRIMARY KEY NOT NULL,
    ID_COMPANY INT DEFAULT 0,
    PURCHASE_HT INT DEFAULT 0,
    PURCHASE_TTC INT DEFAULT 0
)

